insert into model_repo(model_type ,function_name ,path,y_var_type,display_name ,insert_date ,last_updated_on ) values ('DecisionTreeClassification','DecisionTreeClassification','/Modeling/Assets','Categorical','Decision Tree Classification',current_timestamp(),current_timestamp());
insert into model_repo(model_type ,function_name ,path,y_var_type,display_name ,insert_date ,last_updated_on ) values ('DecisionTreeRegression','DecisionTreeRegression','/Modeling/Assets','Continuous','Decision Tree Regression',current_timestamp(),current_timestamp());
insert into model_repo(model_type ,function_name ,path,y_var_type,display_name ,insert_date ,last_updated_on ) values ('GradientBoosting','GradientBoosting','/Modeling/Assets','Categorical','Gradient Boosting',current_timestamp(),current_timestamp());
insert into model_repo(model_type ,function_name ,path,y_var_type,display_name ,insert_date ,last_updated_on ) values ('LinearRegression','LinearRegression','/Modeling/Assets','Continuous','Linear Regression',current_timestamp(),current_timestamp());
insert into model_repo(model_type ,function_name ,path,y_var_type,display_name ,insert_date ,last_updated_on ) values ('LogisticRegression','LogisticRegression','/Modeling/Assets','Categorical','Logistic Regression',current_timestamp(),current_timestamp());
insert into model_repo(model_type ,function_name ,path,y_var_type,display_name ,insert_date ,last_updated_on ) values ('NeuralNet','NeuralNet','/Modeling/Assets','Categorical','Neural Network',current_timestamp(),current_timestamp());
insert into model_repo(model_type ,function_name ,path,y_var_type,display_name ,insert_date ,last_updated_on ) values ('RandomForest','RandomForest','/Modeling/Assets','Categorical','Random Forest',current_timestamp(),current_timestamp());
insert into model_repo(model_type ,function_name ,path,y_var_type,display_name ,insert_date ,last_updated_on ) values ('RandomForestRegressor','RandomForestRegressor','/Modeling/Assets','Continuous','Random Forest Regressor',current_timestamp(),current_timestamp());
insert into model_repo(model_type ,function_name ,path,y_var_type,display_name ,insert_date ,last_updated_on ) values ('SVM','SVM','/Modeling/Assets','Categorical','Support Vector Machine',current_timestamp(),current_timestamp());
